package com.treasure_data.jdbc.compiler.parser;

import java.io.Reader;

import com.treasure_data.jdbc.compiler.SQLParserException;
import com.treasure_data.jdbc.compiler.stat.Statement;

/**
 * A JSqlParser implementation that uses a parser generated by JavaCC
 */
public class CCSQLParserManager implements SQLParser {

    public Statement parse(Reader statementReader) throws SQLParserException {
        CCSQLParser parser = new CCSQLParser(statementReader);
        try {
            return parser.Statement();
        } catch (Throwable e) {
            throw new SQLParserException(e);
        }
    }

}
